# The status generator command.
# Optional: with no status generator the bar will display only tags and layout name.
command = "i3status-rs"

## Colors
background = "#1a1b26ff" 
color = "#a4add2"
#separator = "#9a8a62ff"
tag_fg = "#54586eff"
tag_bg = "#28282800"
#tag_inactive_fg = "#54586eff"
tag_focused_fg = "#a4add2ff"
tag_focused_bg = "#414868ff"
#tag_urgent_fg = "#282828ff"
#tag_urgent_bg = "#cc241dff"
#tag_inactive_fg = "#54586eff"
#tag_inactive_bg = "#28282800"
#
## The font and various sizes
font = "Fira Code 11"
height = 30
#margin_top = 0
#margin_bottom = 0
#margin_left = 0
#margin_right = 0
separator_width = 0.0
#tags_r = 8.0
tags_padding = 15.0
#tags_margin = 0.0
#blocks_r = 8.0
#blocks_overlap = 0.0

## Misc
#position = "top" # either "top" or "bottom"
#layer = "top" # one of "top", "overlay", "bottom" or "background"
#hide_inactive_tags = true
#invert_touchpad_scrolling = true
#show_tags = true
show_layout_name = false
#blend = true # whether tags/blocks colors should blend with bar's background
show_mode = false
#start_hidden = false # whether the bar is initially in the 'hidden' state
#
## WM-specific options
#[wm.river]
#max_tag = 9 # Show only the first nine tags
#
## Per output overrides
## [output.your-output-name]
## right now only "enable" option is available
## enable = false
##
## You can have any number of overrides
## [output.eDP-1]
## enable = false
