icons_format = "{icon}"

[theme]
theme = "native"
[theme.overrides]
idle_bg = "#1a1b26ff" 
idle_fg = "#a4add2ff"

[icons]
icons = "awesome4"


[[block]]
block = "custom"
interval = 600
command = "curl wttr.in/HongKong?format=3"

[[block]]
block = "battery"
interval = 2
missing_format = ""

[[block]]
block = "net"
interval = 2
format = " $icon $ssid "
[[block.click]]
button = "left"
cmd = "foot -e nmtui"

[[block]]
block = "sound"


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R %Z') "

[[block]]
block = "uptime"
interval = 1

