
plugins: musicbrainz inline convert lyrics fetchart

import:
  write: yes

lyrics:
  auto: yes
  dist_thresh: 0.11
  fallback: null
  force: no
  print: no
  sources: [lrclib]
  synced: yes

musicbrainz:
    data_source_mismatch_penalty: 0.5
    #search_limit: 5
    host: musicbrainz.org
    https: yes
    ratelimit: 1
    ratelimit_interval: 1.0
    extra_tags: []
    genres: no
    external_ids:
        discogs: no
        bandcamp: no
        spotify: no
        deezer: no
        beatport: no
        tidal: no

fetchart:
    sources: 
      - filesystem 
      - coverart: release 
      - lastfm 
      - itunes 
      - coverart: releasegroup
      - amazon 
      - '*'

